### ISSUE TITLE
Skipped hits in src/SANDDigitizationEDEPSIM.cpp using SAND_opt2.gdml geometry.

### ISSUE THREAD

**Issue by denisecasazza** [DUNE/sandreco#28]
In`src/digitization.cpp` hits are skipped due to unexpected volume path. Input files`*edep.root` are created using `SAND_opt2.gdml`geometry  https://github.com/DUNE/sandreco/blob/e4e6a9fac27c74356e496a80238c30caad4e71f4/src/SANDDigitizationEDEPSIM.cpp#L279

**Comment by mt82** [comment]
![Screenshot 2024-06-13 alle 08 22 49](https://github.com/DUNE/sandreco/assets/7208136/7ae03d89-22ef-43eb-9c7b-ad3589f1842c)
The input file is: `/storage/gpfs_data/neutrino/users/dcasazza/lot-of-nue/production_11/events-in-STTtracker.99.edep.root`, the geometry file is: `/storage/gpfs_data/neutrino/users/dcasazza/lot-of-nue/production_12/SAND_opt2.gdml`

**Comment by mt82** [comment]
The naming of the tube name in `/storage/gpfs_data/neutrino/users/dcasazza/lot-of-nue/production_12/SAND_opt2.gdml` don't match with what expected (That geometry is not supported anymore). The name of the path is, for example: 
```
/volWorld_PV_1/rockBox_lv_PV_0/volDetEnclosure_PV_0/volSAND_PV_0/MagIntVol_volume_PV_0/sand_inner_volume_PV_0/STTtracker_PV_0/STT_20_CMod_PV_0/STT_20_CMod_ST_PV_0/STT_20_CMod_ST_hh_PV_0/STT_20_CMod_ST_hh_2straw_PV_396/horizontalST_Ar_PV_1/horizontalST_Ar_air_PV_0
```
The expected path is:
```cpp
const char* const stt_tube_regex_string =
    "(C|C3H6|Trk)Mod_([0-9]+)_plane(XX|YY)_straw_PV_([0-9]+)(/|)";
```
